In [1]:
#Basic mathematics with a numpy array

In [2]:
#importing numpy
import numpy as np

In [3]:
#basic arithmetics
a=np.array([1, 2, 3, 4])

#addition
print("addition -",(a+2))

#subtraction
print("subtraction -",(a-2))

#multiplication
print("multiplication -",(a*2))

#division
print("divition -",(a/2))

addition - [3 4 5 6]
subtraction - [-1  0  1  2]
multiplication - [2 4 6 8]
divition - [0.5 1.  1.5 2. ]


In [4]:
#sum of two arrays
a=np.array([1, 2, 3, 4])
b=np.array([4, 5, 6, 7])
print(a+b)

#same goes with other operations

[ 5  7  9 11]


In [5]:
#power
a=np.array([1, 2, 3, 4])

#a^2
print("a^2-",a**2)

#a^3
print("a^3-",a**3)

a^2- [ 1  4  9 16]
a^3- [ 1  8 27 64]


In [6]:
#trigonometry functions
a=np.array([1, 2, 3, 4])

#sin
print("sin-",np.sin(a))

#cos
print("cos-",np.cos(a))

#tan
print("tan-",np.tan(a))

sin- [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos- [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
tan- [ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [8]:
#matrix multiplication
a=np.ones((2, 3))
print(a, "\n")
b=np.full((3, 2), 2)
print(b, "\n")

print(np.matmul(a, b))

[[1. 1. 1.]
 [1. 1. 1.]] 

[[2 2]
 [2 2]
 [2 2]] 

[[6. 6.]
 [6. 6.]]


In [9]:
#determinant of matrix
a=np.identity(3)
print(np.linalg.det(a))

1.0
