In [3]:
#Accessing/Chnaging specific elements, rows, columns, etc

In [7]:
#importing numpy
import numpy as np

In [23]:
a=np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
#REMEMBER INDEXING STARTS FROM 0 NOT 1

In [24]:
#get a specific element <arrayname>[row_index]
#accessing element in row 2 column 6
print(a[1, 5])

13


In [13]:
#Get specific row
#accessing 1st row
print(a[0, :])

[1 2 3 4 5 6 7]


In [25]:
#Get specific column
#accessing 5th column
print(a[:, 4])

[ 5 12]


In [26]:
#printing elements are particular interval
#<arrayname>[row_num, <startindex>:<endindex>:<intervalsize>]
#<arrayname>[<startindex>:<endindex>:<intervalsize>, col_num]
print(a[0, 1:6:2])
#this will go to the first row
#print elements from index 1 to 6 at an interval of 2 elements

[2 4 6]


In [27]:
#change values of particular elements
#changing value of element at row 2 column 6
print(a,"\n")

a[1, 5]=21
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 21 14]]


In [30]:
#You can also replace entire rows or columns
#replacing column 6
print(a,"\n")

a[:, 5]=[60, 210]
print(a)

#the same goes with rows

[[  1   2   3   4   5  60   7]
 [  8   9  10  11  12 210  14]] 

[[  1   2   3   4   5  60   7]
 [  8   9  10  11  12 210  14]]


In [ ]:
#Everything above also works for 3d numpy arrays