In [1]:
#Basic statistics

In [2]:
#importing numpy
import numpy as np

In [13]:
#min value
stats=np.array([[1, 2, 3], [4, 5, 6]])

print(stats, "\n\n")

#overall min
print(np.min(stats))

#row-wise min
print(np.min(stats, axis=1))

#column wise min
print(np.min(stats, axis=0))

[[1 2 3]
 [4 5 6]] 


1
[1 4]
[1 2 3]


In [14]:
#max value
stats=np.array([[1, 2, 3], [4, 5, 6]])

print(stats, "\n\n")

#overall max
print(np.max(stats))

#row-wise max
print(np.max(stats, axis=1))

#column wise max
print(np.max(stats, axis=0))

[[1 2 3]
 [4 5 6]] 


6
[3 6]
[4 5 6]


In [15]:
#sum of elements
stats=np.array([[1, 2, 3], [4, 5, 6]])

print(stats, "\n\n")

#overall sum
print(np.sum(stats))

#row-wise sum
print(np.sum(stats, axis=1))

#column wise sum
print(np.sum(stats, axis=0))

[[1 2 3]
 [4 5 6]] 


21
[ 6 15]
[5 7 9]
