In [1]:
#Reorganizing arrays

In [2]:
#importing numpy
import numpy as np

In [6]:
#reshaping an array
before=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(before, "\n")

after=before.reshape((10, 1))       #new r and c should have same number of values
print(after)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [8]:
#vertically stacking vectors
v1=np.array([1, 2, 3, 4])
print(v1)
v2=np.array([5, 6, 7, 8])
print(v2, "\n")

v3=np.vstack([v1, v2])
print(v3)

[1 2 3 4]
[5 6 7 8] 

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#horizontally stacking vectors
h1=np.array([1, 2, 3, 4])
print(v1)
h2=np.array([5, 6, 7, 8])
print(v2, "\n")

h3=np.hstack([h1, h2])
print(v3)

[1 2 3 4]
[5 6 7 8] 

[1 2 3 4 5 6 7 8]
