In [1]:
#Initializing different types of arrays

In [2]:
#importing numpy
import numpy as np

In [15]:
#all 0s matrix

#1d matrix
print("1d matrix-\n",np.zeros(5))

#2d matrix
print("\n\n2d matrix-\n",np.zeros((3, 3)))

#3d matrix
print("\n\n3dmatrix -\n",np.zeros((2, 3, 3)))

1d matrix-
 [0. 0. 0. 0. 0.]


2d matrix-
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3dmatrix -
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [3]:
#all 1s matrix

#1d matrix
print("1d matrix-\n",np.ones(5))

#2d matrix
print("\n\n2d matrix-\n",np.ones((3, 3)))

#3d matrix
print("\n\n3dmatrix -\n",np.ones((2, 3, 3)))

1d matrix-
 [1. 1. 1. 1. 1.]


2d matrix-
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3dmatrix -
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
#any other number
#np.full((r, c), number)
print(np.full((2,2), 100))   

#you can also pass the shape on a previously existing matrix
a=np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print("\n", np.full(a.shape, 99))

[[100 100]
 [100 100]]

 [[99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]]


In [12]:
#matrix of random numbers
print(np.random.rand(4, 2))

#if you want to pass in the shape of a pre-existing array
print("\n", np.random.random_sample(a.shape))

#the random numbers generated will be between 0 and 1

[[0.94710742 0.98285129]
 [0.42049549 0.63489596]
 [0.58300986 0.47343975]
 [0.97769778 0.40077323]]

 [[0.94240382 0.50767927 0.23945188 0.52815793 0.17691464 0.43168447
  0.9076021 ]
 [0.99358691 0.71366905 0.75677775 0.53834806 0.96950986 0.66303168
  0.26509373]]


In [17]:
#random integer values
#np.random.ranint(<startValue>, <endValue>, size)
#                 optional      compulsory  compulsory
#If start value is not given then 0 will be considered as start value

#with start value
print(np.random.randint(2, 8, size=(3,3)))

#without start value
print("\n", np.random.randint(9, size=(3,3)))

[[3 5 3]
 [6 2 7]
 [2 2 7]]

 [[1 2 8]
 [2 7 5]
 [2 5 8]]


In [18]:
#identity matrix
#pass dimesion of square matrix
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
#repeat a numpy array
a=np.array([1, 2, 3])
new_a=np.repeat(a, 4)       #argument is name of the array, the number of times the element is to be repeated
print(new_a)

#you can also change the way the elements are printed
#the above showed the elements being printed the given number of times before moving to the next element
#to change the order of printin you have to use a 2d matrix

a=np.array([[1, 2, 3]])     #considered a 2d matrix with same values
new_a=np.repeat(a, 4, axis=0)       #axis will define which way it is printed
print("\n", new_a)

[1 1 1 1 2 2 2 2 3 3 3 3]

 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [25]:
#create a copy of existing array
a=np.array([4, 5, 6])
b=a.copy()
print(b)

[4 5 6]


In [ ]:
#be careful whilst copying.
#if you just assign withput using the copy function then changes made in new array will apply to original array.