In [1]:
#Basics of numpy

In [17]:
#importing numpy
import numpy as np

In [2]:
#printing a 1d numpy array
a=np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
#printing 2d numpy array
b=np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
#Get dimension of numpy array
print(a.ndim)
print(b.ndim)

1
2


In [7]:
#Get shape of the array
print(a.shape)             #thie first one will only give us one value becuase the output is a vector
print(b.shape)

(3,)
(2, 3)


In [15]:
#Get datatype, size and total sizeof memory  used by numpy array

#datatype
print(a.dtype)
print(b.dtype)
#These datatypes are by default

print("\n")

#size
print(a.itemsize)
print(b.itemsize)

print("\n")

#total size
print(a.nbytes)
print(b.nbytes)

int32
float64


4
8


12
48


In [16]:
#we can also specify which dataytpe the array should use
c=np.array([9, 10, 11], dtype="int16")

#datatype
print(c.dtype)

#size
print(c.itemsize)

#total size
print(c.nbytes)

int16
2
6
